name: drp
description: "Driver Reputation Passport"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.3
  http: ^1.2.2
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  animate_do: ^3.3.4
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#4A90E2"
  image: assets/logo.png
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"